# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 21:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=200)),
                ('website_url', models.CharField(max_length=1000)),
                ('website_cms', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='website_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.Website'),
        ),
    ]
